name: tests

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        allow-prereleases: true
    - run: python -m pip install tox
    - run: |
        git config --global init.defaultBranch main
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
    - run: tox -e py
